### ISSUE TITLE
Sign in to your Tableau Server failed. Please check URL and credentials.

### ISSUE THREAD

**Issue by dijikul** [tableau/TabMigrate#8]
Authentication not working with Active Directory Integration.

I'm unable to authenticate against our Tableau server using our tool to extract the content.  We're AD integrated.
![image](https://cloud.githubusercontent.com/assets/2670528/19820905/b5799368-9d18-11e6-80cb-bf1cfaf573e6.png)

**Comment by IvoSalmreTableau** [comment]
How are you specifying your domain name?  --- Even if the server uses integrated authentication, you must explicitly specify the Windows Domain Name and Password (the REST APIs don't use integrated authentication - they require the password to be explicitly stated during sign in)

**Comment by anirudhpunuru** [comment]
Hey Ivo, 

Does this work with SAML integrated Tableau server? I did create a local user(like we use in tabcmd), gave me the sign in failed error. It also gave me the same error when I used the SAML username and pass. 

Thoughts ?

**Comment by chris-brownNexmo** [comment]
I found that I got the error when using (server):
https://<subdomain>.<my_website>.com
but it worked with:
https://<subdomain>.<my_website>.com/#/projects
we have the server (not split into sites) so I am not sure if that effects it?

**Comment by IvoSalmreTableau** [comment]
Thanks for pointing out the problem.  -- I was assuming there was a "#" in the URL.  -- I just fixed the problem (in v1.12) -- should work fine now.   thanks! -ivo

**Comment by manticor24** [comment]
I am also experiencing this issue, for what it's worth.

**Comment by vinaytukka** [comment]
any workaround to login into server with SAML configuration. While i am able to login into Non SAML server, not able to loginto server with SAML configuration.

**Comment by kravitej** [comment]
Hi, I'm still facing the same issue.Sign in to your Tableau Server failed. Please check URL and credentials. I'm using V1.13

**Comment by piyum24** [comment]
Can anyone help point me in the right direction? I have active directory enabled on Tableau server, I'm able to log on the server as a server admin, but I can't log on TabMigrate (error message screenshot below). 

I've tried typing the URL as: 
- https://tableau.COMPANYNAME.com
- https://tableau.COMPANYNAME.com/#/
- https://tableau.COMPANYNAME.com/#/projects


![image](https://user-images.githubusercontent.com/43389412/45714722-4933be00-bb47-11e8-8605-c43ab42b2820.png)

**Comment by alitwaij** [comment]
I had it too , turned out i had installed the wrong release. So use older one if current doesnt work
